---
- name: Create App directory
  hosts: nodes
  gather_facts: true
  become: true
  tasks:
    - name: Make App directory
      ansible.builtin.file:
        path: '/tmp/app'
        state: directory
        mode: '0777'
    
    - name: Copy App to Kubernetes Nodes
      ansible.builtin.copy:
        src: './app/'
        dest: '/tmp/app/'
        mode: '0777'

- name: Apply Helm Chart
  hosts: master
  gather_facts: true
  become: true
  tasks:
    - name: Make Helm directory
      ansible.builtin.file:
        path: '/tmp/helm'
        state: directory
        mode: '0755'

    - name: Copy Helm chart to Kubernetes Master Node
      ansible.builtin.copy:
        src: './helm/'
        dest: '/tmp/helm/'
        mode: '0755'

    - name: Execute Helm chart
      ansible.builtin.shell: helm upgrade --install --namespace default --set image.tag="{{ imageTag }}" testapp /tmp/helm/

