apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["tail"]
        args: [-f", "/dev/null"]
#        command: ["sh"]
#        args: ["-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:3003"]
        ports:
        - containerPort: 3003
        env:
        - name: DB_HOST
          value: "db"
        - name: DB_NAME
          value: "tutorial-dev"
        - name: DB_USER
          value: "vinhle"
        - name: DB_PASS
          value: "password"
        volumeMounts:
            - name: app-volume
              mountPath: /app
      volumes: 
        - name: app-volume
          hostPath: 
            path: /tmp/app
            type: DirectoryOrCreate  
